### ISSUE TITLE
Ability to include bad line in InvalidJson()

### ISSUE THREAD

**Issue by JoshHighland** [raphaelstolt/json-lines#10]
it would be helpful to include the ability to include the malformed JSON in InvalidJson(). 

Right now when the exception is thrown I am blind to the line that caused it. It would be helpful to see where the problem is, so it can be fixed upstream.

I think that an optional flag added to delineEachLineFromFile() would be a clean way to do it

thanks!

**Comment by raphaelstolt** [comment]
Fixed with 4358bd67b6eeff0689c7864f0c152cad3c22d870.
