### ISSUE TITLE
PHP 5.5 support?

### ISSUE THREAD

**Issue by project707** [raphaelstolt/json-lines#3]
Hi Raphael, As simple as it is, this is a great tool that i think will greatly aid us in our transition to more purpose built big data platforms and associated languages. Thank you.

As far as the problem at hand... we ran into this issue where the requirement is >= PHP 5.6. We are on 5.5 currently, so we have to bypass the platform requirements with --ignore-platform-req (which isn't great to have to instruct everyone on the team to do), but it doesn't seem as though this is necessary so far. Is there some functionality that requires 5.6 specifically?

**Comment by raphaelstolt** [comment]
PHP support was dropped with release `2.0.0`. If you need PHP 5.5 support do a `composer require stolt/json-lines:"^1.0"`. 

There's no functionality that requires 5.6 specifically, but I don't want to support EOL PHP [versions](http://php.net/supported-versions.php). Also there were [no functional changes](https://github.com/raphaelstolt/json-lines/compare/v1.0.0...v2.0.0) between `1.0.0` and `2.0.0`. 

Not sure yet if bug fixes will be merged into `^1.0` releases, therefore my recommendation is to upgrade your PHP version in the __very__ near future.
